# Generated by Django 4.2.5 on 2023-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_about_course_link_logo_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.AlterField(
            model_name='stat',
            name='number',
            field=models.IntegerField(),
        ),
    ]
