# Generated by Django 4.2.5 on 2023-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_about_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
