# Generated by Django 4.2.5 on 2023-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_stat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='suffix',
            field=models.CharField(default='wefdg', max_length=10),
        ),
        migrations.AlterField(
            model_name='stat',
            name='number',
            field=models.IntegerField(),
        ),
    ]
