# Generated by Django 4.2.5 on 2023-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_stat_suffix_alter_stat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='suffix',
            field=models.CharField(default='+', max_length=10),
        ),
    ]
