# Generated by Django 4.2.5 on 2023-09-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_stat_suffix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='desciption',
            new_name='description',
        ),
    ]
