# Generated by Django 4.2.5 on 2023-09-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_desciption_stat_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='popularity',
            new_name='feature',
        ),
    ]
